name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ Spaceship_Move_Test, Spaceship_Rotate_Test, master, MacroBuilderSolid, EndMoveCommand, GameCommand, Stateful, Endpoint, AdapterGenerator, InterpretationMessage, InitializeNewGame, CreateGameStrategy, ooaip ]
  pull_request:
    branches: [ Spaceship_Move_Test, Spaceship_Rotate_Test, master, MacroBuilderSolid, EndMoveCommand, GameCommand, Stateful, Endpoint, AdapterGenerator, InterpretationMessage, InitializeNewGame, CreateGameStrategy, ooaip ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
          #- name: Test
          # run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=../coverage/ -p:CoverletOutputFormat=opencover ./Spaceship.IoC.Test.No.Strategies
          #- name: Codecov
          #uses: codecov/codecov-action@v3.1.1
      - name: Install dotnet-gcdump
        run: dotnet tool install --global dotnet-gcdump
      - name: Run dotnet-gcdump 
        run: dotnet-test & ps axf | grep dotnet | grep -v grep | awk '{print  "dotnet-gcdump collect -o .gcdump -p " $1}' | sh
      - name: Out
        run: ls -l .gcdump
      - name: Archive gcdump results
        uses: actions/upload-artifact@v4
        with:
          name: .gcdump
          path: .gcdump
    
